version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Port des Webpack-Servers innerhalb des Containers (Host:Container)
    volumes:
      - ./:/app # Binden des gesamten Nx-Monorepo-Verzeichnisses mit dem Container ein